---
kind: pipeline
name: bahc_ohana_api

platform:
  os: linux
  arch: amd64

services:
  - name: database
    image: mdillon/postgis:10
    environment:
      POSTGRES_DB: ohana_api_test
      POSTGRES_USER: postgres
    ports:
      - 5432

#   - name: chrome
#     image: robcherry/docker-chromedriver
#     ports:
#       - 4444

  - name: elasticsearch
    image: elasticsearch:5-alpine
    ports:
      - 9200

steps:
  - name: test
    image: alpine:3.8
    commands:
      - apk add curl
      - sleep 20
      - curl http://elasticsearch:9200

  - name: tests
    image: ruby:2.5.3
    environment:
      API_PATH: api
      ADMIN_PATH: admin
      ASSET_HOST: example.com
      DEFAULT_PER_PAGE: '30'
      DOMAIN_NAME: example.com
      MAX_PER_PAGE: '50'
      RAILS_ENV: test
      DOCKER_CI: true
      OHANA_API_ENDPOINT: http://ohana-api-test.herokuapp.com/api
      ELASTICSEARCH_URL: http://elasticsearch:9200 # This gets set in chewy.rb file.
      ADMIN_APP_TOKEN: testing123
    commands:
      - apt-get update -qy && apt-get install apt-transport-https
      - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt stretch-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get update && apt-get install -y nodejs libnss3 postgresql-client-10
      - gem install bundler --conservative
      - bundle check || bundle install --jobs 20 --retry 5
      - cp config/drone.database.yml config/database.yml
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt-get install -y ./google-chrome-stable_current_amd64.deb
      - mkdir /chromedriver
      - wget -q --continue -P /chromedriver "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84"
      - wget -q --continue -P /chromedriver "https://chromedriver.storage.googleapis.com/$(cat /chromedriver/LATEST_RELEASE_84)/chromedriver_linux64.zip"
      - unzip /chromedriver/chromedriver* -d /chromedriver
      - PATH=/chromedriver:$PATH
      - chromedriver -v
      - sleep 15
      - RAILS_ENV=test bundle exec rake db:create && bundle exec rake db:migrate
      - RAILS_ENV=test bundle exec rspec spec

trigger:
  event:
    - pull_request
