version: "2"
services:
  database:
    image: circleci/postgres:9.6-alpine-postgis
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  ruby:
    image: ussba/cc-ruby:2.5.3
    volumes:
      - .:/repo
    environment:
      # DATABASE_URL:
      # HUBZONE_API_DB_USER: postgres
      # HUBZONE_API_DB_PASSWORD: postgres
      DATABASE_URL: postgres://root:postgres@database.local/ohana_api_test
      API_PATH: api
      ADMIN_PATH: admin
      DEFAULT_PER_PAGE: 30
      MAX_PER_PAGE: 50
      ASSET_HOST: localhost
      DOMAIN_NAME: localhost
      EXPIRES_IN: 0
      TLD_LENGTH: 0
      ENABLE_HTTPS: "no"
      SECRET_TOKEN: CLOSERBYCHAINSMOKERSBUTEVERYLYRICISREPLACEDBYALLSTARBYSMASHMOUTH
      RAILS_ENV: test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
    command: sleep 100000
    links:
      - "database:database.local"
