---
version: 2
workflows:
  version: 2
  tests:
    jobs:
      - rubocop
          # filters:
          #   branches:
          #     only:
          #     - ^feature
          #     - ^bugfix
      - rspec
          # filters:
          #   branches:
          #     only:
          #     - ^feature
          #     - ^bugfix
jobs:
  rubocop:
    docker:
      - image: ussba/cc-ruby:2.5.3
    working_directory:
      ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run rubocop
          command: |
            bundle exec rubocop .
  rspec:
    docker:
      - image: ussba/cc-ruby:2.5.3
        environment:
        #   DATABASE_URL:
        #   HUBZONE_API_DB_USER: postgres
        #   HUBZONE_API_DB_PASSWORD: postgres
          DATABASE_USER: root
          DATABASE_PASSWORD: postgres
          API_PATH: api
          ADMIN_PATH: admin
          DEFAULT_PER_PAGE: 30
          MAX_PER_PAGE: 50
          ASSET_HOST: localhost
          DOMAIN_NAME: localhost
          EXPIRES_IN: 0
          TLD_LENGTH: 0
          ENABLE_HTTPS: "no"
          SECRET_TOKEN: CLOSERBYCHAINSMOKERSBUTEVERYLYRICISREPLACEDBYALLSTARBYSMASHMOUTH
          RAILS_ENV: test
      # Also need postgress to test stuff
      - image: circleci/postgres:9.6-alpine-postgis
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Run Tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            #TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rake db:create db:migrate db:seed
            pg_restore -c --no-owner -d ohana_api_test data/ohana_api_development.dump
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              spec

      # Collect Reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results