---
version: 2
workflows:
  version: 2
  tests:
    jobs:
      - rubocop:
          filters:
            branches:
              only:
                - /^feature\/
                - /^bugfix\/
      - rspec: 
          filters:
            branches:
              only:
                - /^feature\/
                - /^bugfix\/

jobs:
  rubocop:
    docker:
      - image: ussba/cc-ruby:2.5.3
    working_directory:
      ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run rubocop
          command: |
            bundle exec rubocop .
  rspec:
    docker:
      - image: ussba/cc-ruby:2.5.3
        environment:
          HUBZONE_API_DB_USER: postgres
          HUBZONE_API_DB_PASSWORD: postgres
          RAILS_ENV: test
      # Also need postgress to test stuff
      - image: circleci/postgres:9.6-alpine-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Run Tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            #TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rake db:create db:migrate
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              spec

      # Collect Reports
     - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results